### ISSUE TITLE
How to launch?

### ISSUE THREAD

**Issue by beizhengren** [samialperen/ros2_move_robot#4]
When I run the command like this:
```shell
# ros2 launch ros2_draw_squares
 move_robot_in_squares_service_server.launch.py
```
I meet an error as following:

```shell
file 'move_robot_in_squares_service_server.launch.py' was not found in the share directory of package 'ros2_draw_squares' which is at '/home/wyz/my-ros2/ws_wyz/install/ros2_draw_squares/share/ros2_draw_squares'
```
How could I resolve it? 
Thanks

**Comment by samialperen** [comment]
@beizhengren seems like you have not sourced your workspace. You can read what does it mean and how to do it [here[(https://docs.ros.org/en/foxy/Tutorials/Beginner-Client-Libraries/Creating-A-Workspace/Creating-A-Workspace.html#source-ros-2-environment)

I am closing the issue. Feel free to reopen it if sourcing the workspace does not solve it.
